# Generated by Django 3.1 on 2020-08-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200827_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
