# Generated by Django 3.1.2 on 2020-10-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201006_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
